// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCe0xjBHTTJ1fym1AV2cCrdQW_1kWaP2dI',
    appId: '1:183889078127:web:85ae0f7dc28ba4a59e6a9a',
    messagingSenderId: '183889078127',
    projectId: 'skillconnect-c5ed3',
    authDomain: 'skillconnect-c5ed3.firebaseapp.com',
    storageBucket: 'skillconnect-c5ed3.firebasestorage.app',
    measurementId: 'G-Y8DM61Q0Z8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbJwGwVFcHiNI-YWQCXWzX-DXvdfwMeLQ',
    appId: '1:183889078127:android:b065cb7ee16c323b9e6a9a',
    messagingSenderId: '183889078127',
    projectId: 'skillconnect-c5ed3',
    storageBucket: 'skillconnect-c5ed3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCX8JKvTingSqJOvYWaSdT7D3hMKbOgsv0',
    appId: '1:183889078127:ios:daac3a578e1b3c5f9e6a9a',
    messagingSenderId: '183889078127',
    projectId: 'skillconnect-c5ed3',
    storageBucket: 'skillconnect-c5ed3.firebasestorage.app',
    iosBundleId: 'com.example.skillconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCX8JKvTingSqJOvYWaSdT7D3hMKbOgsv0',
    appId: '1:183889078127:ios:daac3a578e1b3c5f9e6a9a',
    messagingSenderId: '183889078127',
    projectId: 'skillconnect-c5ed3',
    storageBucket: 'skillconnect-c5ed3.firebasestorage.app',
    iosBundleId: 'com.example.skillconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCe0xjBHTTJ1fym1AV2cCrdQW_1kWaP2dI',
    appId: '1:183889078127:web:06624b6fb5a48e559e6a9a',
    messagingSenderId: '183889078127',
    projectId: 'skillconnect-c5ed3',
    authDomain: 'skillconnect-c5ed3.firebaseapp.com',
    storageBucket: 'skillconnect-c5ed3.firebasestorage.app',
    measurementId: 'G-G2WR4JB9EH',
  );
}
